name: navigation_detector
description: A Flutter plugin to detect if Android is using gesture navigation or button navigation.
version: 0.0.1
homepage: https://github.com/Virakyuth-PK/navigation_detector
repository: https://github.com/Virakyuth-PK/navigation_detector

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.loba.navigation_detector
        pluginClass: NavigationDetectorPlugin